.TH "back" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
back \- Back
.PP
An easing function that has a 'cute' natural coming back effect\&.  

.SH "Detailed Description"
.PP 
An easing function that has a 'cute' natural coming back effect\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBbackIn\fP"
.br
.RI "\fIAcceelerate initial values with a 'back' equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBbackOut\fP"
.br
.RI "\fIDeaccelerate ending values with a 'back' equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBbackInOut\fP"
.br
.RI "\fIAcceelerate initial and deaccelerate ending values with a 'back' equation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
