.TH "bounce" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bounce \- Bounce
.PP
A bouncing easing function\&. Values 'bounce' around the maximum/minumum\&.  

.SH "Detailed Description"
.PP 
A bouncing easing function\&. Values 'bounce' around the maximum/minumum\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBbounceIn\fP"
.br
.RI "\fIAcceelerate initial values with a 'bounce' equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBbounceOut\fP"
.br
.RI "\fIDeaccelerate ending values with a 'bounce' equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBbounceInOut\fP"
.br
.RI "\fIAcceelerate initial and deaccelerate ending values with a 'bounce' equation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
