.TH "circular" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
circular \- Circular
.PP
A smooth, circular slope that resembles the arc of an circle\&.  

.SH "Detailed Description"
.PP 
A smooth, circular slope that resembles the arc of an circle\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBcircularIn\fP"
.br
.RI "\fIAcceelerate initial values with a circular equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBcircularOut\fP"
.br
.RI "\fIDeaccelerate ending values with a circular equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBcircularInOut\fP"
.br
.RI "\fIAcceelerate initial and deaccelerate ending values with a circular equation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
