.TH "cubic" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cubic \- Cubic
.PP
A bit curvier than the quadratic easing\&.  

.SH "Detailed Description"
.PP 
A bit curvier than the quadratic easing\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBcubicIn\fP"
.br
.RI "\fIAaccelerate initial values with a cubic equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBcubicOut\fP"
.br
.RI "\fIDeaccelerate ending values with a cubic equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBcubicInOut\fP"
.br
.RI "\fIAcceelerate initial and deaccelerate ending values with a cubic equation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
