.TH "easings" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
easings \- Easings
.PP
Bundled easing functions based on \fCRobert Penner's Easing Functions\fP  

.SH "Detailed Description"
.PP 
Bundled easing functions based on \fCRobert Penner's Easing Functions\fP 

You should plug these functions into \fBtweeny::tween::via\fP function to specify the easing used in a tween\&. 
.PP
\fBSee also:\fP
.RS 4
\fBtweeny::easing\fP 
.RE
.PP

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBLinear\fP"
.br
.RI "\fIThe most boring ever easing function\&. It has no acceleration and change values in constant speed\&. \fP"
.ti -1c
.RI "\fBQuadratic\fP"
.br
.RI "\fIThe most commonly used easing functions\&. \fP"
.ti -1c
.RI "\fBCubic\fP"
.br
.RI "\fIA bit curvier than the quadratic easing\&. \fP"
.ti -1c
.RI "\fBQuartic\fP"
.br
.RI "\fIA steeper curve\&. Acceleration changes faster than Cubic\&. \fP"
.ti -1c
.RI "\fBQuintic\fP"
.br
.RI "\fIAn even steeper curve\&. Acceleration changes really fast\&. \fP"
.ti -1c
.RI "\fBSinuisodal\fP"
.br
.RI "\fIA very gentle curve, gentlier than quadratic\&. \fP"
.ti -1c
.RI "\fBExponential\fP"
.br
.RI "\fIA very steep curve, based on the \fCp(t) = 2^(10*(t-1))\fP equation\&. \fP"
.ti -1c
.RI "\fBCircular\fP"
.br
.RI "\fIA smooth, circular slope that resembles the arc of an circle\&. \fP"
.ti -1c
.RI "\fBBack\fP"
.br
.RI "\fIAn easing function that has a 'cute' natural coming back effect\&. \fP"
.ti -1c
.RI "\fBElastic\fP"
.br
.RI "\fIAn elastic easing function\&. Values go a little past the maximum/minimum in a elastic effect\&. \fP"
.ti -1c
.RI "\fBBounce\fP"
.br
.RI "\fIA bouncing easing function\&. Values 'bounce' around the maximum/minumum\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
