.TH "elastic" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elastic \- Elastic
.PP
An elastic easing function\&. Values go a little past the maximum/minimum in a elastic effect\&.  

.SH "Detailed Description"
.PP 
An elastic easing function\&. Values go a little past the maximum/minimum in a elastic effect\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBelasticIn\fP"
.br
.RI "\fIAcceelerate initial values with an 'elastic' equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBelasticOut\fP"
.br
.RI "\fIDeaccelerate ending values with an 'elastic' equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBelasticInOut\fP"
.br
.RI "\fIAcceelerate initial and deaccelerate ending values with an 'elastic' equation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
