.TH "exponential" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exponential \- Exponential
.PP
A very steep curve, based on the \fCp(t) = 2^(10*(t-1))\fP equation\&.  

.SH "Detailed Description"
.PP 
A very steep curve, based on the \fCp(t) = 2^(10*(t-1))\fP equation\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBexponentialIn\fP"
.br
.RI "\fIAcceelerate initial values with an exponential equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBexponentialOut\fP"
.br
.RI "\fIDeaccelerate ending values with an exponential equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBexponentialInOut\fP"
.br
.RI "\fIAcceelerate initial and deaccelerate ending values with an exponential equation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
