.TH "linear" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linear \- Linear
.PP
The most boring ever easing function\&. It has no acceleration and change values in constant speed\&.  

.SH "Detailed Description"
.PP 
The most boring ever easing function\&. It has no acceleration and change values in constant speed\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBlinear\fP"
.br
.RI "\fIValues change with constant speed\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
