.TH "quadratic" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
quadratic \- Quadratic
.PP
The most commonly used easing functions\&.  

.SH "Detailed Description"
.PP 
The most commonly used easing functions\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBquadraticIn\fP"
.br
.RI "\fIAccelerate initial values with a quadratic equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBquadraticOut\fP"
.br
.RI "\fIDeaccelerate ending values with a quadratic equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBquadraticInOut\fP"
.br
.RI "\fIAcceelerate initial and deaccelerate ending values with a quadratic equation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
