.TH "quartic" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
quartic \- Quartic
.PP
A steeper curve\&. Acceleration changes faster than Cubic\&.  

.SH "Detailed Description"
.PP 
A steeper curve\&. Acceleration changes faster than Cubic\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBquarticIn\fP"
.br
.RI "\fIAcceelerate initial values with a quartic equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBquarticOut\fP"
.br
.RI "\fIDeaccelerate ending values with a quartic equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBquarticInOut\fP"
.br
.RI "\fIAcceelerate initial and deaccelerate ending values with a quartic equation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
