.TH "quintic" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
quintic \- Quintic
.PP
An even steeper curve\&. Acceleration changes really fast\&.  

.SH "Detailed Description"
.PP 
An even steeper curve\&. Acceleration changes really fast\&. 


.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBquinticIn\fP"
.br
.RI "\fIAcceelerate initial values with a quintic equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBquinticOut\fP"
.br
.RI "\fIDeaccelerate ending values with a quintic equation\&. \fP"
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBquinticInOut\fP"
.br
.RI "\fIAcceelerate initial and deaccelerate ending values with a quintic equation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
