.TH "sinuisodal" 3 "Mon Jul 18 2016" "Version 1.0.0" "Tweeny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sinuisodal \- Sinuisodal
.PP
A very gentle curve, gentlier than quadratic\&.  
A very gentle curve, gentlier than quadratic\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Tweeny from the source code\&.
